
                -- ============================================
                -- Create Databse
                -- ============================================

CREATE DATABASE customer_behaviour_db;
USE customer_behaviour_db;

                 -- ============================================
                 -- Create table
                 -- ============================================

DROP TABLE IF EXISTS customer_info ;
CREATE TABLE customer_info (
    customer_id                   INT,
    age                           INT,
    gender                        VARCHAR(50),
    item_purchased                VARCHAR(50),
    category                      VARCHAR(50),
    purchase_amount               VARCHAR(50),
    location                      VARCHAR(50),
    size                          VARCHAR(50),
    color                         VARCHAR(50),
    season                        VARCHAR(50),
    review_rating                 FLOAT,
    subscription_status           VARCHAR(50),
    shipping_type                 VARCHAR(50),
    discount_applied              VARCHAR(50),
    promo_code_used               VARCHAR(50),
    previous_purchases            VARCHAR(50),
    payment_method                VARCHAR(50),
    frequency_of_purchases        VARCHAR(50),
    age_group                     VARCHAR(50),
    frequency_purchase_days       INT

);


                 -- ============================================
                 -- Insert/Load data into table and check table
                 -- ============================================
SELECT 
    *
FROM dbo.customer_table;        -- load successfull

                 -- ============================================
                 -- sql queries and get outcome of questions
                 -- ============================================

--Q1. What is the total revenue generated by male vs. female customers?

SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM dbo.customer_table
GROUP BY gender;

-- ----------------------------------------------------------------------------------------------------------------
--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT
    customer_id,
    purchase_amount
FROM dbo.customer_table
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM dbo.customer_table);


-- ----------------------------------------------------------------------------------------------------------------
-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating),2) AS avg_review_rating
FROM dbo.customer_table
GROUP BY item_purchased
ORDER BY ROUND(AVG(review_rating),2) DESC ;


-- ----------------------------------------------------------------------------------------------------------------
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM dbo.customer_table
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- ----------------------------------------------------------------------------------------------------------------

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(subscription_status) as number_of_subs,
    AVG(purchase_amount) AS avg_spent,
    SUM(purchase_amount) AS total_revenue
FROM dbo.customer_table
GROUP BY subscription_status;


 -- ----------------------------------------------------------------------------------------------------------------

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

        SELECT TOP 5
            item_purchased,
            ROUND(SUM(CASE 
                WHEN discount_applied = 'Yes' THEN 1.0
            ELSE 0 END )/COUNT(*) *100 ,2)  AS discount_applyrate
        FROM dbo.customer_table
        GROUP BY item_purchased 
        ORDER BY discount_applyrate DESC;
 
  -- ----------------------------------------------------------------------------------------------------------------

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with cte_segment as (                                            -- use CTE 
SELECT
    customer_id,
    previous_purchases,
    CASE                                                         -- divide into diff segments
        WHEN previous_purchases > 25 THEN 'Loyal'
        WHEN previous_purchases > 5 and previous_purchases <= 25 THEN 'Returning'
    ELSE 'New'
    end as customer_segment
FROM dbo.customer_table
)
select 
    COUNT(customer_id) AS total_customer,                          -- main query
    customer_segment
from cte_segment
GROUP BY customer_segment;

 -- ----------------------------------------------------------------------------------------------------------------

--Q8. What are the top 3 most purchased products within each category? 

WITH cte_category AS (
        SELECT
            category,
            COUNT(customer_id) AS total_customers,
            item_purchased,
            ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) desc) AS rank_
        FROM dbo.customer_table
        GROUP BY category,item_purchased
)
SELECT
    category,
    total_customers,
    item_purchased,
    rank_
FROM cte_category
WHERE rank_ <= 3;

 -- ----------------------------------------------------------------------------------------------------------------

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    COUNT(customer_id) AS total_customers,
    subscription_status
FROM dbo.customer_table
WHERE previous_purchases >5
GROUP BY subscription_status;
 -- ----------------------------------------------------------------------------------------------------------------

--Q10. What is the revenue contribution of each age group? 

SELECT
    SUM(purchase_amount) AS total_revenue,
    age_group
FROM dbo.customer_table
GROUP BY age_group
ORDER BY total_revenue DESC;
 -- ----------------------------------------------------------------------------------------------------------------
-- >>>>>>>>>>
            --> All Questions Answers are here in forms of SQL queries 
            --> know lets move for Graphical representations and analysis nd all >>>>>>>>..




